ansible-playbook-keepass: check keepass checkout version
Check the version of the supplied keepass checkout to make sure no old
credentials are being deployed.

To keep this mechanism effective, we must bump .keepass_version as
necessary from now on.

diff --git a/ansible/ansible-playbook-keepass b/ansible/ansible-playbook-keepass
--- a/ansible/ansible-playbook-keepass
+++ b/ansible/ansible-playbook-keepass
@@ -7,6 +7,8 @@ export ANSIBLE_NOCOWS=1
 # and store it if entered. 
 #
 KEEPASS_FILE_CONFIG=".keepass_file_path"
+KEEPASS_VERSION_CONFIG=".keepass_version"
+
 if [ -z "${KEEPASS}" -a -r "${KEEPASS_FILE_CONFIG}" ]; then
   KEEPASS=`cat ${KEEPASS_FILE_CONFIG} | xargs`
 
@@ -22,6 +24,19 @@ fi
 if [ -z "${KEEPASS}" ]; then
   echo -n "Keepass file path (…voc.kdbx): "
   read -r KEEPASS
+fi
+
+KEEPASS_DIR=$(dirname "${KEEPASS}")
+if [ -f "${KEEPASS_VERSION_CONFIG}" ]; then
+  KEEPASS_REQUIRED_VERSION=$(cat "${KEEPASS_VERSION_CONFIG}")
+  GIT_DIR="${KEEPASS_DIR}/.git" git merge-base --is-ancestor $KEEPASS_REQUIRED_VERSION HEAD
+
+  if [ $? -ne 0 ]; then
+    echo "keepass checkout must be newer or equal to ${KEEPASS_REQUIRED_VERSION}, which it isn't"
+    echo "do a git pull before continuing"
+
+    exit 1
+  fi
 fi
 
 if [ -z "${KEEPASS_FILE_CONFIG}" -o ! -f "${KEEPASS}" -o ! -r "${KEEPASS}" ]; then
